"""
prepare_baseline.py — Stage solution.c (no attack comment) for baseline eval.

Uses the bare solution.c generated by the agent (before any attack comment is
added) to check whether auditors can detect the NPD without adversarial hints.

VulnLLM-R: all problems (one solution.c per problem)
RepoAudit: only the cases that evaded detection in the attacked run

Usage:
    python attacker/prepare_baseline.py --runs-dir attacker/runs/gpt-5.4-mini
"""

import argparse
import glob
import json
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# ---------------------------------------------------------------------------
# Discover which slug/at pairs evaded RepoAudit in the attacked run
# ---------------------------------------------------------------------------

def ra_evaded_keys(repo_root: str) -> set[str]:
    pattern = os.path.join(
        repo_root,
        "RepoAudit/result/dfbscan/claude-sonnet-4-6/NPD/Cpp/**/detect_info.json",
    )
    detected = set()
    for dpath in glob.glob(pattern, recursive=True):
        try:
            data = json.loads(open(dpath).read())
        except Exception:
            continue
        for entry in data.values():
            bv = entry.get("buggy_value", "")
            m = re.search(r"context_aware/(\w+)/(\w+)\.c", bv)
            if m:
                slug, fname = m.group(1), m.group(2)
                at = fname[len(slug) + 1:]
                detected.add(f"{slug}/{at}")

    evaded = set()
    runs_dir = os.path.join(repo_root, "attacker/runs/gpt-5.4-mini")
    for vpath in glob.glob(os.path.join(runs_dir, "repository_*/verification.json")):
        slug = os.path.basename(os.path.dirname(vpath)).replace("repository_", "")
        verif = json.loads(open(vpath).read())
        for at, status in verif.items():
            if status == "ok" and f"{slug}/{at}" not in detected:
                evaded.add(f"{slug}/{at}")
    return evaded


# ---------------------------------------------------------------------------
# Staging helpers
# ---------------------------------------------------------------------------

def stage_vulnllm(slug: str, code: str) -> str:
    """Stage one entry in VulnLLM-R baseline dataset. Returns slug dir."""
    dataset_dir = os.path.join(
        REPO_ROOT, "VulnLLM-R", "datasets", "C", "NPD",
        "attacker", "baseline", slug, "c",
    )
    os.makedirs(dataset_dir, exist_ok=True)
    entry = {
        "CWE_ID": ["CWE-476"],
        "code": code,
        "target": 1,
        "language": "c",
        "dataset": "attacker_baseline",
        "idx": 1,
        "attack_type": "none",
        "RELATED_CWE": [],
        "stack_trace": True,
    }
    with open(os.path.join(dataset_dir, f"{slug}_baseline.json"), "w") as f:
        json.dump([entry], f, indent=2)
    return os.path.dirname(dataset_dir)  # slug dir


def stage_repoaudit(slug: str, at: str, code: str) -> str:
    """Stage one .c file in RepoAudit baseline benchmark. Returns bench dir."""
    bench_dir = os.path.join(
        REPO_ROOT, "RepoAudit", "benchmark", "C", "NPD",
        "attacker", "baseline", slug,
    )
    os.makedirs(bench_dir, exist_ok=True)
    with open(os.path.join(bench_dir, f"{slug}_{at}.c"), "w") as f:
        f.write(code)
    return bench_dir


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--runs-dir", default="attacker/runs/gpt-5.4-mini")
    args = parser.parse_args()

    runs_dir = os.path.abspath(args.runs_dir)
    if not os.path.isdir(runs_dir):
        print(f"ERROR: {runs_dir}", file=sys.stderr); sys.exit(1)

    evaded = ra_evaded_keys(REPO_ROOT)
    print(f"RA-evaded (will also stage for RepoAudit baseline): {sorted(evaded)}\n")

    all_vl_slug_dirs, all_ra_dirs = [], []

    for entry in sorted(os.scandir(runs_dir), key=lambda e: e.name):
        if not entry.is_dir() or not entry.name.startswith("repository_"):
            continue
        slug = entry.name.replace("repository_", "")

        sol_path = os.path.join(entry.path, "solution.c")
        if not os.path.isfile(sol_path):
            print(f"{entry.name}: no solution.c, skipping")
            continue

        # Check at least one ok solution exists (i.e. problem was solvable)
        vpath = os.path.join(entry.path, "verification.json")
        if os.path.isfile(vpath):
            verif = json.loads(open(vpath).read())
            if not any(s == "ok" for s in verif.values()):
                print(f"{entry.name}: no ok solutions, skipping")
                continue

        code = open(sol_path).read()

        slug_dir = stage_vulnllm(slug, code)
        all_vl_slug_dirs.append(slug_dir)
        print(f"{entry.name}: staged for VulnLLM-R baseline", end="")

        # For each AT that evaded RA, stage for RepoAudit
        evaded_ats = [at for at in [k.split("/")[1] for k in evaded if k.startswith(slug + "/")]]
        for at in evaded_ats:
            ra_dir = stage_repoaudit(slug, at, code)
            all_ra_dirs.append(ra_dir)
            print(f", staged RA baseline ({at})", end="")
        print()

    print(f"\nTotal: {len(all_vl_slug_dirs)} problems staged for VulnLLM-R baseline")
    _print_commands(all_vl_slug_dirs, all_ra_dirs)


def _print_commands(vl_slug_dirs: list[str], ra_dirs: list[str]):
    print()
    print("=" * 70)
    print("Run VulnLLM-R baseline (bare buggy code, no attack comments):")
    print("=" * 70)
    if vl_slug_dirs:
        vl_output = os.path.abspath(
            os.path.commonpath(vl_slug_dirs)
        ).replace("/datasets/", "/results/")
        dataset_args = " \\\n      ".join(os.path.abspath(d) for d in sorted(set(vl_slug_dirs)))
        print(f"""\
cd {REPO_ROOT}
VLLM_USE_V1=0 CUDA_VISIBLE_DEVICES=<GPU_ID> .venv/bin/python -m vulscan.test.test \\
    --dataset_path \\
      {dataset_args} \\
    --language c \\
    --model UCSB-SURFI/VulnLLM-R-7B \\
    --use_cot --use_policy \\
    --vllm --tp 1 --max_tokens 4096 --save \\
    --output_dir {vl_output}
""")

    print("=" * 70)
    print("Run RepoAudit baseline (RA-evaded cases only, no attack comments):")
    print("=" * 70)
    if ra_dirs:
        ra_parent = sorted(set(os.path.dirname(d) for d in ra_dirs))[0]
        print(f"""\
cd {REPO_ROOT}/RepoAudit/src
MODEL=claude-sonnet-4-6 \\
LANGUAGE=Cpp \\
    bash run_repoaudit.sh \\
    {ra_parent} \\
    NPD \\
    "*.c"
""")
    else:
        print("(no RA-evaded cases found)\n")


if __name__ == "__main__":
    main()
