#!/usr/bin/env bash
# install_vulweaver_deps.sh — one-time, NO-SUDO, NO-CONDA install for the
# VulWeaver cvebench C/C++ pipeline. Everything is self-contained:
#   - Python deps  -> a dedicated uv venv ($REPO/.venv-vulweaver)
#   - graphviz     -> compiled from source into a local prefix (pygraphviz links it;
#                     graphviz here is only a DOT parser for Joern's exported graphs)
#   - JDK 21       -> portable Temurin tarball (Joern is a JVM tool; system java is 11)
# Inspect, then run it yourself (one ~2-5 min graphviz build + a few downloads).
#
# Pipeline is C/C++ only (Language.C, --lang c; the Java semantic-model stage is gated off).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GV_VER="${GV_VER:-9.0.0}"
GV_PREFIX="${GV_PREFIX:-/mnt/ssd/aryawu/graphviz-$GV_VER}"
JDK_DIR="${JDK_DIR:-/mnt/ssd/aryawu/temurin-21}"
JOERN_DIR="${JOERN_DIR:-/mnt/ssd/aryawu/joern-2.0.260}"
ASTYLE_VER="${ASTYLE_VER:-3.4.13}"   # >=3.4 needed: VulWeaver passes --squeeze-ws
ASTYLE_PREFIX="${ASTYLE_PREFIX:-/mnt/ssd/aryawu/astyle}"
VENV="${VENV:-$REPO_ROOT/.venv-vulweaver}"
BUILD_DIR="${BUILD_DIR:-/mnt/ssd/aryawu/_vulweaver_build}"
ENV_FILE="$REPO_ROOT/scripts/oneoff/.vulweaver_env.sh"
mkdir -p "$BUILD_DIR"

echo "### 1/5  uv venv (python 3.11) -> $VENV"
[[ -x "$VENV/bin/python" ]] || uv venv --python 3.11 "$VENV"

echo "### 2/5  build graphviz $GV_VER from source -> $GV_PREFIX  (cgraph/cdt for pygraphviz)"
if [[ ! -f "$GV_PREFIX/lib/pkgconfig/libcgraph.pc" ]]; then
    cd "$BUILD_DIR"
    [[ -f "graphviz-$GV_VER.tar.gz" ]] || curl -L \
        "https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/$GV_VER/graphviz-$GV_VER.tar.gz" \
        -o "graphviz-$GV_VER.tar.gz"
    rm -rf "graphviz-$GV_VER"
    tar xzf "graphviz-$GV_VER.tar.gz"
    cd "graphviz-$GV_VER"
    # Minimal build: we only need the core libs (cgraph/cdt/gvc) + headers, not
    # renderers/bindings/GUI. Missing optional deps just disable features.
    ./configure --prefix="$GV_PREFIX" --disable-swig --without-x --without-qt \
        --without-gtk --without-gdk --without-poppler --without-rsvg \
        --without-pangocairo --without-gts --without-webp --quiet
    make -j"$(nproc)"
    make install
fi

echo "### 3/5  portable Temurin JDK 21 -> $JDK_DIR  (Joern needs JDK 19+)"
if [[ ! -x "$JDK_DIR/bin/java" ]]; then
    mkdir -p "$JDK_DIR"
    curl -L "https://api.adoptium.net/v3/binary/latest/21/ga/linux/x64/jdk/hotspot/normal/eclipse?project=jdk" \
        -o "$BUILD_DIR/temurin21.tar.gz"
    tar xzf "$BUILD_DIR/temurin21.tar.gz" -C "$JDK_DIR" --strip-components=1
fi

echo "### 4/5  Joern CLI v2.0.260 -> $JOERN_DIR"
if [[ ! -x "$JOERN_DIR/joern-cli/joern-parse" ]]; then
    mkdir -p "$JOERN_DIR"
    curl -L "https://github.com/joernio/joern/releases/download/v2.0.260/joern-cli.zip" \
        -o "$JOERN_DIR/joern-cli.zip"
    unzip -q -o "$JOERN_DIR/joern-cli.zip" -d "$JOERN_DIR"
fi

echo "### 4b/5  build astyle $ASTYLE_VER -> $ASTYLE_PREFIX/bin  (VulWeaver shells out to it)"
if [[ ! -x "$ASTYLE_PREFIX/bin/astyle" ]]; then
    mkdir -p "$ASTYLE_PREFIX/bin"
    cd "$BUILD_DIR"
    [[ -f "astyle-$ASTYLE_VER.tar.gz" ]] || curl -fsSL \
        "https://gitlab.com/saalen/astyle/-/archive/$ASTYLE_VER/astyle-$ASTYLE_VER.tar.gz" \
        -o "astyle-$ASTYLE_VER.tar.gz"
    rm -rf "astyle-$ASTYLE_VER"; tar xzf "astyle-$ASTYLE_VER.tar.gz"
    ASRC="$(dirname "$(tar tzf "astyle-$ASTYLE_VER.tar.gz" | grep -E 'src/astyle_main\.cpp$' | head -1)")"
    # astyle is self-contained C++ — compile directly, no cmake/make needed.
    g++ -O2 -std=c++17 -o "$ASTYLE_PREFIX/bin/astyle" "$BUILD_DIR/$ASRC"/*.cpp
fi

echo "### 5/5  python deps into the uv venv (pygraphviz built against local graphviz)"
# pkg-config + rpath let pygraphviz find graphviz at build AND run time.
export PKG_CONFIG_PATH="$GV_PREFIX/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
export LDFLAGS="-Wl,-rpath,$GV_PREFIX/lib -L$GV_PREFIX/lib ${LDFLAGS:-}"
export CFLAGS="-I$GV_PREFIX/include ${CFLAGS:-}"
# VulWeaver's requirements.txt is internally inconsistent: it pins networkx<3.3
# but scubatrace (any version) requires networkx>=3.3. VulWeaver's actual nx
# usage (compose/DiGraph/MultiDiGraph/subgraph/nx_agraph.read_dot/nodes/edges)
# all exist in 3.3+, so we override the cap. scubatrace is only *used* on the
# Java path (target.py:621) — we just need it importable for C.
OVERRIDES="$BUILD_DIR/uv-overrides.txt"
echo "networkx>=3.3,<3.5" > "$OVERRIDES"
VIRTUAL_ENV="$VENV" uv pip install --upgrade pip
VIRTUAL_ENV="$VENV" uv pip install -r "$REPO_ROOT/VulWeaver/requirements.txt" --override "$OVERRIDES"

echo "### writing env file -> $ENV_FILE  (sourced by run_vulweaver_cvebench.sh)"
cat > "$ENV_FILE" <<EOF
# Auto-generated by install_vulweaver_deps.sh — source before running the pipeline.
source "$VENV/bin/activate"
export JAVA_HOME="$JDK_DIR"
export PATH="$JDK_DIR/bin:$ASTYLE_PREFIX/bin:\$PATH"
export JOERN_PATH="$JOERN_DIR/joern-cli"
export LD_LIBRARY_PATH="$GV_PREFIX/lib:\${LD_LIBRARY_PATH:-}"
export PKG_CONFIG_PATH="$GV_PREFIX/lib/pkgconfig:\${PKG_CONFIG_PATH:-}"
EOF

echo
echo "### DONE. Smoke-test, then run:"
echo "    source $ENV_FILE"
echo "    export OPENROUTER_API_KEY=<your key>"
echo "    java -version                                   # expect 21 (Temurin)"
echo "    \"\$JOERN_PATH/joern-parse\" --version            # smoke-test Joern"
echo "    python -c 'import pygraphviz, cpu_heater, scubatrace; print(\"py deps OK\")'"
echo "    scripts/oneoff/run_vulweaver_cvebench.sh 5      # 5-slug smoke test, then drop the 5 for all 128"
